### ISSUE TITLE
linkifyHTML detect url wrongly by combining encoded html space

### ISSUE THREAD

**Issue by haoyuchen1992** [SoapBox/linkifyjs#174]
## Usage case

Input HTML String -> `<BR>&nbsp; <BR>https://www.google.com&nbsp; <BR>`

After running linkifyHTML,:

**Expected:** `<bR><a href="https://www.google.com&nbsp" class="linkified" target="_blank">https://www.google.com</a>&nbsp; <bR>`
![image](https://cloud.githubusercontent.com/assets/5420789/19582731/c55da0e0-96eb-11e6-8973-bf0bae0cea17.png)

**Actual:** `<bR><a href="https://www.google.com&nbsp" class="linkified" target="_blank">https://www.google.com&nbsp</a>; <bR>`
![image](https://cloud.githubusercontent.com/assets/5420789/19582715/ac30fdec-96eb-11e6-9705-66e135176346.png)

As you can see, it treats `&nbsp` as part of url, therefore it make the `;` visiable.

**Comment by haoyuchen1992** [comment]
Update: I tried to use linkify-element, it wouldn't give me this error,

**Comment by nfrasser** [comment]
Fixed, will be released with v2.1.4.

Note for the curious, I fixed only the `&nbsp;` case (no other HTML named character references) because `&nbsp;` counts as whitespace. All other named-character references will be part of the URL due to the `http(s)://` protocol at the beginning: It forces everything that follows (up to the next whitespace or punctuation) to be part of the URL regardless of its format.
