### ISSUE TITLE
What RegEx does Linkify use?

### ISSUE THREAD

**Issue by iTayGNR** [SoapBox/linkifyjs#193]
Hello.
I'm trying to build a script in PHP that is similar to what Linkify does.
It should find URLs within a string and apply a custom function on the matches.
The thing is, I can't find "the perfect" RegEx. 
I would like to know how does Linkify find URLs, and if it's a regex.

Thank You!

**Comment by nfrasser** [comment]
Hi @iTayGNR, while this perfect regex you're looking for does theoretically exist, it's not defined explicitly in the codebase. Linkify uses a two-stage [scanner based on Finite State Machines](https://en.wikipedia.org/wiki/Lexical_analysis#Scanner), the underlying model that powers regular expressions. Using state machines rather than regular expressions allows Linkify to differentiate between URLs, email addresses, "@" mentions, etc. with single theoretical regular expression.

If you insist on using regular expressions, there are [plenty of good suggestions on StackOverflow](http://stackoverflow.com/search?q=regular+expression+url).

Hope that helps.

**Comment by iTayGNR** [comment]
Thank for your response.
Is there any option how can I use this scanner in my PHP script?

You see, I'm trying to find URLs in a given string, and apply a function for all of them.
currently I'm using 
`'#(www\.|https?://)?[a-z0-9]+\.[a-z0-9]{2,4}\S*#i'`
but in case of a string like `google.co.uk (main site: google.com)`, it matches the closing bracket as a part of the URL while Linkify does not.

That is why I'm trying to build something similar to Linkify scanner..

**Comment by nfrasser** [comment]
If it helps, here are Linkify's state machine transition definitions that handle opening/closing brackets: https://github.com/SoapBox/linkifyjs/blob/5bc1eebe4dc167526957e622088cf0462848320e/src/linkify/core/parser.js#L191-L251
