### ISSUE TITLE
Striping off for invalid URL

### ISSUE THREAD

**Issue by mifas** [SoapBox/linkifyjs#266]
If I enter below invalid URL, it's stripping off the character and return valid link. 

`https://!@#ce.google.com`
to
`https://ce.rakuten.co.jp`

The expected behavior is should not consider as a link

[Demo](https://codesandbox.io/s/kx2n5ow485)

**Comment by nfrasser** [comment]
This is the expected behaviour. 

What's actually happening here is linkify is seeing that `https://!@#` is not the beginning of valid URL, so it ignores it. However, everything that follows (`ce.google.com`) is a totally valid URL without a protocol prefix.

![image](https://user-images.githubusercontent.com/1693461/54616389-f2476c80-4a35-11e9-91c6-c7594e5797ae.png)

If you'd like to disable links that don't start with `http://` or `https://`, you can filter them out of the `find` results or use the `validate` option:

```js
let links = linkify.find(str, "url")
  .filter(link => /https?:\/\//.test(link.value))

linkifyStr(str, { 
  validate: { 
    url: value => /https?:\/\//.test(value) 
  } 
})
```
