### ISSUE TITLE
Links are added to urls that already have <a> tags around them

### ISSUE THREAD

**Issue by emilyuhde** [Soapbox/linkifyjs#336]
1. Go to the Linkify demo page: https://soapbox.github.io/linkifyjs/
2. On example # 2 where you can add your own string to test, add in some text that has links, such as: `The site <a href="https://github.com">github.com</a> is <a href="#awesome">#awesome</a>.` and click the Linkify button.

The output looks like this: `The site <a href="https://github.com">github.com</a> is <a href="#awesome">#awesome</a>.` where "https://github.com">github.com</a>" is a link.

I would expect that the library could detect opening and closing <a> tags and ignore them and anything between them.

**Comment by nfrasser** [comment]
Hi @emilyuhde, this is intentional for the [linkify-string](https://soapbox.github.io/linkifyjs/docs/linkify-string.html) interface - it assumes that all input text is plain and contains no HTML. If you need to parse text with HTML, try the [linkify-html](https://soapbox.github.io/linkifyjs/docs/linkify-html.html) interace.
