### ISSUE TITLE
post-? queries pick up trailing parenthesis

### ISSUE THREAD

**Issue by dmassant** [SoapBox/linkifyjs#81]
Thanks for the great library, man - this have been very helpful.

I'm getting a strange behavior in a corner case and wanted to let you know:
 - works: https://www.youtube.com/watch?v=4KbSRXP0wik
 - works: (https://www.youtube.com)
 - does not work: (https://www.youtube.com/watch?v=4KbSRXP0wik)

In the last case, that trailing parenthesis gets picked up in the url.

**Comment by nfrasser** [comment]
Hi @dmassant, this behaviour is intentional, due to the fact that some URLs contain parentheses. e.g., https://en.wikipedia.org/wiki/Blur_(band). We've already had a few issues regarding this problem, such as #52. Determining whether to include or to exclude a trailing parens from a URL would require some additional lexical analysis that may degrade this plugin's performance. This post goes more into detail about that: http://blog.codinghorror.com/the-problem-with-urls/

We _have_ looked at several ways and tricks to solving this problem, such as a flag that's set when there are parens in the query string. However, these will take some time to implement, and again, we don't want to degrade performance.

For now, I can't offer a real workaround other than ensuring URLs are padded with whitespace.
